[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
  environment = { NODE_VERSION = "16.17.0" }
  [functions]
  directory = "functions"
  node_bundler = "esbuild"
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.google.com https://www.googletagmanager.com https://www.gstatic.com https://analytics.google.com 'unsafe-inline' https://www.google-analytics.com; object-src 'none'; frame-ancestors 'none'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; frame-src 'self'; img-src 'self' data: https://www.google-analytics.com; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://analytics.google.com fonts.googleapis.com;"
    Cache-Control = "no-store"
[[_redirects]]
  from = "/*"
  status = 200
  to = "/.netlify/functions/render"
[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "build/"